### PR TITLE
feat(health): create seperate ping route for quick connection checks

### PR DESCRIPTION
**Pull request by ghost**
# Description

By having a dedicated route that does minimal processing we can significantly reduce the time for our online connection checks and reduce frustration.

The previous health check takes a long time as internally it pings google as well as checking it's disk and memory usage; all of which are slow processes.

This PR adds a new endpoint `/ping` which simply returns the current timestamp, and changes the FE to use it for connection checks

800x quicker 😮 

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Evidence / Demo

## `/health` timings
image

## `/ping` timings
image

# How Has This Been Tested?

**Test Configuration**:
* Browser: Firefox
* Device: 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

### CODE REVIEW

**Review by harristomy — APPROVED** [review]
I love speed

**Review by yuliapechorina — CHANGES_REQUESTED** [review]
The ping throws an error and I'm permanently offline:
```
Access to fetch at 'http://localhost:3333/ping' from origin 'http://localhost:4200' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://uoa-supervision.org' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
Could you enable CORS for localhost:4200? Currently, CORS is only enabled for the production front end. When I change this the ping works for me.

**Review by yuliapechorina — COMMENTED** [review]
Still doesn't work for me, same error (I have definitely pulled)
image

**Review by yuliapechorina — APPROVED** [review]
😍 Works for me now. I'm glad we have this because the health endpoint never worked for me locally (always said insufficient disk space even though I have plenty)

**Review by harristomy — APPROVED** [review]

**Pull request merged**
