### PR TITLE
docs(all): add documentation

### PR DESCRIPTION
**Pull request by ghost**
# Description

Adds lots of documentation goodness. I'm really tired of writing documentation and don't want to type out everything I documented so please just have a good read of the new [README](https://github.com/University-of-Auckland-SOFTENG761/project-team-1/tree/docs/c4-diagram) and the new [documentation](https://github.com/University-of-Auckland-SOFTENG761/project-team-1/blob/docs/c4-diagram/apps/c4-diagram/docs/README.md)

You can use this checklist to help review: https://c4model.com/review/

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change ~~requires~~ **is** a documentation update

# Evidence / Demo

# How Has This Been Tested?

**Test Configuration**:
* Browser:
* Device: 

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

### CODE REVIEW

**Review by uoa-lzha989 — COMMENTED** [review]
All looking really good, just two things from me from when I was very scared of the backend :""""") otherwise excellent work, very comprehensive documentation! 🙌

**Review by harristomy — APPROVED** [review]
This is very detailed and well-documented, great job! Just had a few questions on the RxDB docs. I'll probably have another read through of this in the evening once the performance PR is finalized in case anything is changed and/or has to be documented if it's too obscure.

**Review by uoa-lzha989 — APPROVED** [review]
looking good, few minor things but i don't want to make you wait once they're good to go so putting approval here, if anything changes I'll let you know :)

**Review by butterplup — APPROVED** [review]
LGTM

**Review by yuliapechorina — APPROVED** [review]
LGTM!

**Review by kand198 — APPROVED** [review]
Awesome work @jcha-686 I'm really stoked with how this turned out.

**Pull request merged**
