### PR TITLE
feat(auth, core): authentication and authorisation

### PR DESCRIPTION
**Pull request by ghost**
# Description

Adds the ability to log into the application through auth0.
Allows graphql resolvers to be restricted to logged in users or to logged in supervisors.

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Evidence / Demo

# How Has This Been Tested?

1. Setup `.env` file with the following new values:
```
AUTH0_ISSUER_URL=https://dev-6mx9ad29.us.auth0.com/
AUTH0_AUDIENCE=api.akl-bus.vision
AUTH0_DOMAIN=dev-6mx9ad29.us.auth0.com
AUTH0_CLIENT_ID=SiqwTzesySraxm8Ml8t7wModRdckoh0c
AUTH0_CLIENT_SECRET=e0syIW2CRwbeyKp9wiK-kXDsYSsVdjw506_IMczsXG-BRXBDP9bAk4HUnTUR1aqf
AUTH0_MANAGEMENT_ID=wDTBfLqe71tIgaDp9V2KNYmf1a4KsOwi
AUTH0_MANAGEMENT_SECRET=dzkJPeuPG9DgDRqpZ_rjjO52Yk6XjSodOwaQu-t5ErdlMX2U8nQBWrKlDxzQxpCq
AUTH0_MANAGEMENT_CONNECTION=Username-Password-Authentication
AUTH0_REDIRECT_URI=https://localhost:3333
```
2. Try call the `me` query (student scoped) and `createUser` mutation (supervisor scoped). Ensure they give an unauthorised error.
3. open a web-browser and visit https://dev-6mx9ad29.us.auth0.com/authorize?response_type=code&client_id=SiqwTzesySraxm8Ml8t7wModRdckoh0c&redirect_uri=https://localhost:3333&scope=openid
4. Sign in with credentials:
```
Email: john.smith@example.com
Password: password@123
```
5. After signing in, copy the code in the url query string. i.e. `https://localhost:3333/?code=7ltyh5rKnLFSSPvFvCsob7X3ckCvx9HpHVld7GDul6tik`, the code is `7ltyh5rKnLFSSPvFvCsob7X3ckCvx9HpHVld7GDul6tik`
6. Obtain the id token using the following graphql query:
```graphql
mutation {
  authorizationCodeGrant(code: "<code>"){
 	idToken 
  }
}
```
7. Set the HTTP Headers tab at the bottom of the graphql playground to use the id token
```json
{
  "Authorization": "Bearer <token>"
}
```
8. Create a user in your local database using the auth0id `auth0|631882d521d7b4c72ecbda9f` (the auth0id for the John Smith user). Make this user a **student**
9. You should now be able to successfully call the `me` query. Ensure it returns the same id as the user you just made.
10. The `createUser` mutation should still give an unauthorised error.
11. Change the user to a supervisor and check that you can create a new user.
12. Set the user to inactive and check it doesn't work
13. Delete the user (by adding a timestamp to deleted field) and check it doesn't work

**Test Configuration**:
* Browser: Firefox
* Device: Desktop

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

### CODE REVIEW

**Review by hmit106 — APPROVED** [review]
Overall L(very)GTM, made a comment about one small thing but doesn't really need fixing. Great effort with this PR.

Tested according to instructions on ubuntu/firefox

**Review by harristomy — CHANGES_REQUESTED** [review]
Gonna do more testing tmrw, but some comments and changes added

**Review by yuliapechorina — CHANGES_REQUESTED** [review]
LGTM!

I followed your testing steps and everything worked (on Windows & Chrome). 

As Harris already mentioned, it'd be good to see more detailed error messages for creating a user e.g. insecure password, as the first time I tried the `createUser` mutation it failed. I got a `Bad Request: PasswordNoUserInfoError: Password contains user information` error.
Happy to approve when this is added 😄

**Review by yuliapechorina — APPROVED** [review]
LGTM!

**Review by harristomy — APPROVED** [review]

**Pull request merged**
