### PR TITLE
feat(core): deploy application on GCP

### PR DESCRIPTION
**Pull request by ghost**
# Description

Deploys the backend and frontend on GCP when pushes to main occur.

### Backend
https://api.uoa-supervision.org
* Hosted on google kubernetes engine (GKE)
* Uses helm for package management
* Github package registry used to hold docker image
* Ingress is used to expose the service
* Static IP reserved and pointed at by DNS A record

### Frontend
https://uoa-supervision.org
* Hosted on google storage as a public bucket with a website configuration
* DNS CNAME record points to storage url

### CI/CD
* On push to main both backend and frontend will be built and deployed
* On pushing a tag, backend will be built

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Evidence / Demo

image
image
image

# How Has This Been Tested?

**Test Configuration**:
* Browser:
* Device: 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

### CODE REVIEW

**Review by harristomy — DISMISSED** [review]
I have no idea on the Helm stuff and 90% of the K8S lol, so if you have records of what documentation you used I can have a look over them later in case anything's been missed, cuz this is so much to absorb haha. Looks good to me though, and I've attached two minor comments.

**Review by harristomy — APPROVED** [review]
Sweet as!

**Review by yuliapechorina — COMMENTED** [review]
I'm probably not of much use for most of this PR because I have no idea what's going on, so just reviewing functionality. 

The FE deployment is taking me to the offline page (because the API health check is returning a 502 response).

**Review by yuliapechorina — APPROVED** [review]
Its working for me now 🚀

**Pull request merged**
